# Generated by Django 6.0.2 on 2026-03-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplementStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='type',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE')], max_length=100),
        ),
    ]
