# Generated by Django 6.0.5 on 2026-06-03 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=101)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=51)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=101)),
                ('specialty', models.CharField(choices=[('cardiologist', 'CARDIOLOGIST'), ('dermatologist', 'DERMATOLOGIST'), ('neurologist', 'NEUROLOGIST')], max_length=51)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('institution', models.CharField(max_length=101)),
                ('completed_appointments', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=101)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('cardiology', 'CARDIOLOGY'), ('dermatology', 'DERMATOLOGY'), ('neurology', 'NEUROLOGY')], max_length=51)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], default='scheduled', max_length=51)),
                ('datetime', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('responsible_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_appointments', to='hospital_app.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor')),
            ],
            options={
                'unique_together': {('appointment', 'doctor')},
            },
        ),
    ]
