# Generated by Django 6.0.2 on 2026-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agent_completed_sales_alter_agent_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
